# Generated by Django 3.2.21 on 2023-11-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20231018_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch',
            options={'verbose_name_plural': 'Watches'},
        ),
    ]
