# Generated by Django 3.2.21 on 2023-11-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_date_review_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='body',
        ),
    ]
